import React from 'react'
import PropertyImageGallery from '../component/property-images'
import { useParams } from "react-router-dom";
import PropertyPage from '../component/PropertyDetailBox';
import SimilarPropertiesSection from '../component/SimilarProperty';
import Footer from '../component/footer';
import Navbar from '../component/Navbar';

const Property_detail = () => {
  const initialProperties = [
  {
    id: 1,
    title: "Sun‑drenched 3BHK with Garden Views",
    type: "Apartment",
    transactionType: "Sale",
    price: 7500000,
    priceLabel: "₹75 Lac",
    negotiable: true,
    city: "Ujjain",
    locality: "Nagziri",
    landmark: "Near Ring Road",
    areaBuiltUp: 1500,
    areaCarpet: 1180,
    bhk: 3,
    baths: 3,
    balconies: 2,
    floor: 6,
    totalFloors: 12,
    furnishing: "Semi‑furnished",
    age: "0–5 years",
    facing: "East",
    photos: [
      "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    floorPlan: null,
    videoUrl: null,
    mapsUrl: "https://maps.google.com",
    amenities: [
      "Lift",
      "24/7 Security",
      "Clubhouse",
      "Children's park",
      "Power backup",
    ],
    parking: "Covered",
    rera: "A‑UJN‑25‑2120",
    tag: "Featured",
  },
  {
    id: 2,
    title: "Vaastu‑friendly Residential Plot in Prime Township",
    type: "Plot/Land",
    transactionType: "Sale",
    price: 2500000,
    priceLabel: "₹25 Lac",
    negotiable: false,
    city: "Ujjain",
    locality: "Indore Road",
    landmark: "Near Divine Valley",
    areaBuiltUp: 1000,
    areaCarpet: 1000,
    bhk: null,
    baths: null,
    balconies: null,
    floor: null,
    totalFloors: null,
    furnishing: "NA",
    age: "New",
    facing: "North‑East",
    photos: [
      "https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    floorPlan: null,
    videoUrl: null,
    mapsUrl: "https://maps.google.com",
    amenities: ["Garden", "Street lights", "Water & electricity lines"],
    parking: "Open",
    rera: "A‑UJN‑25‑2120",
    tag: "New Launch",
  },
  {
    id: 3,
    title: "Premium 4BHK Villa with Private Lawn",
    type: "Villa",
    transactionType: "Sale",
    price: 13500000,
    priceLabel: "₹1.35 Cr",
    negotiable: true,
    city: "Indore",
    locality: "Super Corridor",
    landmark: "Near IT Park",
    areaBuiltUp: 2600,
    areaCarpet: 2100,
    bhk: 4,
    baths: 4,
    balconies: 3,
    floor: 2,
    totalFloors: 2,
    furnishing: "Fully‑furnished",
    age: "New",
    facing: "West",
    photos: [
      "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    floorPlan: null,
    videoUrl: null,
    mapsUrl: "https://maps.google.com",
    amenities: ["Clubhouse", "Swimming pool", "Gym", "24/7 Security"],
    parking: "2 Covered",
    rera: "MP‑RERA‑XXXX",
    tag: "Luxury",
  },
  {
    id: 4,
    title: "Compact 2BHK Flat near City Center",
    type: "Apartment",
    transactionType: "Sale",
    price: 4200000,
    priceLabel: "₹42 Lac",
    negotiable: true,
    city: "Ujjain",
    locality: "Freeganj",
    landmark: "Near Tower Chowk",
    areaBuiltUp: 900,
    areaCarpet: 750,
    bhk: 2,
    baths: 2,
    balconies: 1,
    floor: 3,
    totalFloors: 8,
    furnishing: "Unfurnished",
    age: "5–10 years",
    facing: "North",
    photos: [
      "https://images.pexels.com/photos/1457841/pexels-photo-1457841.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    floorPlan: null,
    videoUrl: null,
    mapsUrl: "https://maps.google.com",
    amenities: ["Lift", "Security", "Covered parking"],
    parking: "Covered",
    rera: "A‑UJN‑25‑2120",
    tag: "",
  },
  {
    id: 5,
    title: "Corner Residential Plot in Gated Township",
    type: "Plot/Land",
    transactionType: "Sale",
    price: 3200000,
    priceLabel: "₹32 Lac",
    negotiable: false,
    city: "Ujjain",
    locality: "Dewas Road",
    landmark: "Near Ring Road Junction",
    areaBuiltUp: 1200,
    areaCarpet: 1200,
    bhk: null,
    baths: null,
    balconies: null,
    floor: null,
    totalFloors: null,
    furnishing: "NA",
    age: "New",
    facing: "East",
    photos: [
      "https://images.pexels.com/photos/220182/pexels-photo-220182.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    floorPlan: null,
    videoUrl: null,
    mapsUrl: "https://maps.google.com",
    amenities: ["Wide roads", "Street lights"],
    parking: "Open",
    rera: "A‑UJN‑25‑2120",
    tag: "",
  },
  {
    id: 6,
    title: "Modern 3BHK Apartment with Club Access",
    type: "Apartment",
    transactionType: "Sale",
    price: 6400000,
    priceLabel: "₹64 Lac",
    negotiable: true,
    city: "Indore",
    locality: "Vijay Nagar",
    landmark: "Near Malls & Offices",
    areaBuiltUp: 1400,
    areaCarpet: 1100,
    bhk: 3,
    baths: 3,
    balconies: 2,
    floor: 7,
    totalFloors: 14,
    furnishing: "Semi‑furnished",
    age: "0–5 years",
    facing: "South",
    photos: [
      "https://images.pexels.com/photos/2988860/pexels-photo-2988860.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    floorPlan: null,
    videoUrl: null,
    mapsUrl: "https://maps.google.com",
    amenities: ["Pool", "Gym", "Clubhouse", "Security"],
    parking: "Covered",
    rera: "MP‑RERA‑XXXX",
    tag: "",
  },
  {
    id: 7,
    title: "1BHK Starter Home near College",
    type: "Apartment",
    transactionType: "Sale",
    price: 2200000,
    priceLabel: "₹22 Lac",
    negotiable: true,
    city: "Ujjain",
    locality: "Nanakhheda",
    landmark: "Near Engineering College",
    areaBuiltUp: 550,
    areaCarpet: 450,
    bhk: 1,
    baths: 1,
    balconies: 1,
    floor: 2,
    totalFloors: 4,
    furnishing: "Semi‑furnished",
    age: "0–5 years",
    facing: "West",
    photos: [
      "https://images.pexels.com/photos/4392274/pexels-photo-4392274.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    floorPlan: null,
    videoUrl: null,
    mapsUrl: "https://maps.google.com",
    amenities: ["Parking", "Lift"],
    parking: "Open",
    rera: "A‑UJN‑25‑2120",
    tag: "Budget",
  },
  {
    id: 8,
    title: "Ready‑to‑move 2BHK House with Terrace",
    type: "House",
    transactionType: "Sale",
    price: 5800000,
    priceLabel: "₹58 Lac",
    negotiable: false,
    city: "Ujjain",
    locality: "Rishi Nagar",
    landmark: "Near Divine Valley",
    areaBuiltUp: 1600,
    areaCarpet: 1300,
    bhk: 2,
    baths: 2,
    balconies: 1,
    floor: 1,
    totalFloors: 1,
    furnishing: "Unfurnished",
    age: "5–10 years",
    facing: "North‑East",
    photos: [
      "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    floorPlan: null,
    videoUrl: null,
    mapsUrl: "https://maps.google.com",
    amenities: ["Terrace", "Parking"],
    parking: "Covered",
    rera: "A‑UJN‑25‑2120",
    tag: "",
  },
  {
    id: 9,
    title: "Commercial Shop on Main Road",
    type: "Commercial",
    transactionType: "Sale",
    price: 9000000,
    priceLabel: "₹90 Lac",
    negotiable: true,
    city: "Ujjain",
    locality: "Freeganj",
    landmark: "Main Market",
    areaBuiltUp: 600,
    areaCarpet: 520,
    bhk: null,
    baths: 1,
    balconies: null,
    floor: 0,
    totalFloors: 3,
    furnishing: "Bare shell",
    age: "0–5 years",
    facing: "East",
    photos: [
      "https://images.pexels.com/photos/3735419/pexels-photo-3735419.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    floorPlan: null,
    videoUrl: null,
    mapsUrl: "https://maps.google.com",
    amenities: ["High street frontage"],
    parking: "Open",
    rera: "A‑UJN‑25‑2120",
    tag: "Commercial",
  },
  {
    id: 10,
    title: "4BHK Independent Bungalow with Garden",
    type: "House",
    transactionType: "Sale",
    price: 15500000,
    priceLabel: "₹1.55 Cr",
    negotiable: true,
    city: "Indore",
    locality: "Old Palasia",
    landmark: "Near Park",
    areaBuiltUp: 3000,
    areaCarpet: 2500,
    bhk: 4,
    baths: 4,
    balconies: 2,
    floor: 2,
    totalFloors: 2,
    furnishing: "Semi‑furnished",
    age: "10+ years",
    facing: "South",
    photos: [
      "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    floorPlan: null,
    videoUrl: null,
    mapsUrl: "https://maps.google.com",
    amenities: ["Garden", "Car parking"],
    parking: "2 Covered",
    rera: "MP‑RERA‑XXXX",
    tag: "Premium",
  },
];

   const { id } = useParams(); // id is a string
  const propertyId = Number(id);

  const property = initialProperties.find((p) => p.id === propertyId);
  if (!property) return <p>Property not found.</p>;
    const images = [
  {
    src: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg?auto=compress&cs=tinysrgb&w=1200",
    label: "Front elevation",
  },
  {
    src: "https://images.pexels.com/photos/1457841/pexels-photo-1457841.jpeg?auto=compress&cs=tinysrgb&w=1200",
    label: "Living room",
  },
  {
    src: "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg?auto=compress&cs=tinysrgb&w=1200",
    label: "Floor plan",
  },
  {
    src: "https://images.pexels.com/photos/5563469/pexels-photo-5563469.jpeg",
    label: "Floor plan",
  },
  {
    src: "https://images.pexels.com/photos/5825538/pexels-photo-5825538.jpeg",
    label: "Floor plan",
  },
  {
    src: "https://images.pexels.com/photos/7163610/pexels-photo-7163610.jpeg",
    label: "Floor plan",
  },
  {
    src: "https://images.pexels.com/photos/3615182/pexels-photo-3615182.jpeg",
    label: "Floor plan",
  },
  {
    src: "https://images.pexels.com/photos/3615182/pexels-photo-3615182.jpeg",
    label: "Floor plan",
  },
  {
    src: "https://images.pexels.com/photos/5570226/pexels-photo-5570226.jpeg",
    label: "Floor plan",
  },
  {
    src: "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg?auto=compress&cs=tinysrgb&w=1200",
    label: "Floor plan",
  },
  {
    src: "https://images.pexels.com/photos/2343465/pexels-photo-2343465.jpeg",
    label: "Floor plan",
  },
  
  
];

 const galleryImages = property.photos.map((src, i) => ({
    src,
    label: property.title,
  }));

  return (
    <div>
      <main className="max-w-7xl mx-auto px-4 lg:px-6 py-8 space-y-8">
        <Navbar/>
        <div className="space mt-20"></div>
            <PropertyImageGallery images={images}  title={property.title} />
            <PropertyPage/>
            {/* rest of the details sections here */}
            <SimilarPropertiesSection/>
            
            
          </main>
          <Footer/>
    </div>
  )
}

export default Property_detail
